version: '3.8'
services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - '80:80'
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment: 
      - NAME=keith
    # ports:
    #   - '5000:5000'
    volumes:
      - ./Server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile