# ./github/workflows/integrate.yml
name: Push images to Dockerhub and deploy on ELastic Beanstalk
on: 
 push:
  branches:
    - master
jobs:
  build_docker_images:
    name: build docker images
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-actions@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v1
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-it: ${{secrets.AWS_ACCESS_KEY}}
          aws-secrete-access-key: ${{secrets.AWS_ACCESS_SECRET_KEY}}
          aws-region: us-east-1
      - name: Build and push Client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            keithkfield/bog_frontend:latest
            keithkfield/bog_frontend:1.0.0   
      - name: Build and push Server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            keithkfield/bog_server:latest
            keithkfield/bog_server:1.0.0 
      - name: Build and push Server
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            keithkfield/nginx:latest
            keithkfield/nginx:1.0.0
      - name: AWS Elastic Beanstalk cli
        # You may pin to the exact commit or the version.
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          # eb <command>
          command: eb init --region us-east-1 tester
