# THIS IS WHAT MY GITHUB ACTION LOOKS LIKE ATM
name: Push images to Dockerhub and deploy on ELastic Beanstalk
on: 
 push:
  branches:
    - master
jobs:
  build_docker_images:
    name: build docker images
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        uses: docker/login-action@v1.8.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKERHUB_TOKEN}}
          # Log out from the Docker registry at the end of a job
          logout: true
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET_KEY}}
          aws-region: us-east-1
      - name: Build and push Server
        run: docker build -t keithkfield/blog-server -f Dockerfile ./Server   
      - name: Push built image to dockerhub
        run: docker tag keithkfield/blog-server keithkfield/blog-server:latest 
      - name: push
        run: docker push keithkfield/blog-server
        # End Of Server
      - name: Build and push Client
        run: docker build -t keithkfield/blog-client -f ./client/Dockerfile ./client   
      - name: Push built image to dockerhub
        run: docker tag keithkfield/blog-client keithkfield/blog-client:latest 
      - name: push
        run: docker push keithkfield/blog-client
        # End Of Client
      - name: Build and push Client
        run: docker build -t keithkfield/blog-nginx -f ./nginx/Dockerfile ./nginx   
      - name: Push built image to dockerhub
        run: docker tag keithkfield/blog-nginx keithkfield/blog-nginx:latest 
      - name: push
        run: docker push keithkfield/blog-nginx
        # End of nginx