# THIS IS WHAT MY GITHUB ACTION LOOKS LIKE ATM
name: Push images to Dockerhub and deploy on ELastic Beanstalk
on: 
 push:
  branches:
    - master
jobs:
  build_docker_images:
    name: build docker images
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true
      - name: Build Server image
        run: docker build -t keithkfield/blog-server -f ./Server/Dockerfile ./Server   
      - name: Tag our Image
        run: docker tag keithkfield/blog-server keithkfield/blog-server:latest 
      - name: Push to dockerhub
        run: docker push keithkfield/blog-server
      - name: Build Client
        run: docker build -t keithkfield/blog-client ./client   
      - name: Tag Image
        run: docker tag keithkfield/blog-client keithkfield/blog-client:latest 
      - name: push
        run: docker push keithkfield/blog-client
      - name: Build Nginx
        run: docker build -t keithkfield/blog-nginx ./nginx   
      - name: Tag Image
        run: docker tag keithkfield/blog-nginx keithkfield/blog-nginx:latest 
      - name: push
        run: docker push keithkfield/blog-nginx
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: blog_series_devops
          environment_name: development
          version_label: "app-d56a-210209_150932"
          region: us-east-1